export const DI_TYPES = {
  UserRepository: Symbol.for("UserRepository"),
  CategoryRepository: Symbol.for("CategoryRepository"),
  NewsRepository: Symbol.for("NewsRepository"),
  SavedNewsRepository: Symbol.for("SavedNewsRepository"),
  UserSourceFollowRepository: Symbol.for("UserSourceFollowRepository"),
  SourceRepository: Symbol.for("SourceRepository"),
  TwitterAccountRepository: Symbol.for("TwitterAccountRepository"),
  TwitterAccountFollowRepository: Symbol.for("TwitterAccountFollowRepository"),
  TwitterRepository: Symbol.for("TwitterRepository"),
  PasswordService: Symbol.for("PasswordService"),
  TokenService: Symbol.for("TokenService"),
  IdGenerator: Symbol.for("IdGenerator"),
  CreateUserUseCase: Symbol.for("CreateUserUseCase"),
  AuthenticateUserUseCase: Symbol.for("AuthenticateUserUseCase"),
  GetUserProfileUseCase: Symbol.for("GetUserProfileUseCase"),
  ListNewsUseCase: Symbol.for("ListNewsUseCase"),
  GetNewsByCategoryUseCase: Symbol.for("GetNewsByCategoryUseCase"),
  SaveNewsUseCase: Symbol.for("SaveNewsUseCase"),
  ListSavedNewsUseCase: Symbol.for("ListSavedNewsUseCase"),
  RemoveSavedNewsUseCase: Symbol.for("RemoveSavedNewsUseCase"),
  ListSourcesUseCase: Symbol.for("ListSourcesUseCase"),
  ListFollowedSourcesUseCase: Symbol.for("ListFollowedSourcesUseCase"),
  FollowSourceUseCase: Symbol.for("FollowSourceUseCase"),
  UnfollowSourceUseCase: Symbol.for("UnfollowSourceUseCase"),
  SyncFollowedSourcesUseCase: Symbol.for("SyncFollowedSourcesUseCase"),
  ListCategoriesUseCase: Symbol.for("ListCategoriesUseCase"),
  ListCategoriesWithNewsUseCase: Symbol.for("ListCategoriesWithNewsUseCase"),
  ListFollowedTwitterAccountsUseCase: Symbol.for(
    "ListFollowedTwitterAccountsUseCase"
  ),
  ListTweetsUseCase: Symbol.for("ListTweetsUseCase"),

  TwitterController: Symbol.for("TwitterController"),
};
